version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mysecretuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "15432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    restart: unless-stopped